ebsd = loadEBSD('1_small_area.ang');
plot(ebsd);hold on; 
rectangle( 'Position',  [0 70 20 20]); 
hold off;
ebsd2 = ebsd(inpolygon(ebsd, [0 70 20 20]));
plot(ebsd2);
grains = calcGrains(ebsd2, 'threhold', 5*degree);
grains1 = calcGrains(grains(grainSize(grains) > 10), 'threhold', 5*degree);
plot(ebsd2, 'property', 'iq');
plotKAM(grains1, 'secondorder');
colormap(1-gray);
hold on; 
plotBoundary(grains1, 'property', [0 15],'lineWidth', 3, 'linecolor', 'b');
hold off;
xlabel('ìêì','FontSize', 14);
ylabel('ìêì','FontSize', 14);
KAM = calcKAM(grains, 'secondorder');
%max(KAM);
KAM0 = KAM;
KAM0(KAM>5*degree) = 5*degree;
figure;plot(get(grains,'ebsd'),'property',log(KAM0));
colorbar;
xlabel('ìêì');
ylabel('ìêì');